CREATE TABLE IF NOT EXISTS alm_v3_stress_scenarios (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id BIGINT UNSIGNED NOT NULL,
  stress_code VARCHAR(32) NOT NULL,
  label VARCHAR(128) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  inflow_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  outflow_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_source_mult_d1 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_source_mult_d7 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_source_mult_d30 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_use_mult_d1 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_use_mult_d7 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  liquidity_use_mult_d30 DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  cash_floor_pct_assets DECIMAL(12,6) NULL DEFAULT NULL,
  allow_negative_cash TINYINT(1) NOT NULL DEFAULT 1,
  allow_negative_liquidity_buffer TINYINT(1) NOT NULL DEFAULT 1,
  duration_asset_shift_years DECIMAL(12,6) NOT NULL DEFAULT 0.000000,
  duration_liability_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  own_funds_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  s2_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  cat_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  comments_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_alm_v3_stress_scenarios_profile_code (profile_id, stress_code),
  KEY idx_alm_v3_stress_scenarios_profile (profile_id),
  CONSTRAINT fk_alm_v3_stress_scenarios_profile FOREIGN KEY (profile_id) REFERENCES alm_v3_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alm_v3_stress_asset_class_shocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  stress_scenario_id BIGINT UNSIGNED NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  mv_mult DECIMAL(12,6) NOT NULL DEFAULT 1.000000,
  duration_shift_years DECIMAL(12,6) NOT NULL DEFAULT 0.000000,
  liquidity_source_mult_d1 DECIMAL(12,6) NULL DEFAULT NULL,
  liquidity_source_mult_d7 DECIMAL(12,6) NULL DEFAULT NULL,
  liquidity_source_mult_d30 DECIMAL(12,6) NULL DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_alm_v3_stress_asset_shock (stress_scenario_id, asset_code),
  KEY idx_alm_v3_stress_asset_scenario (stress_scenario_id),
  CONSTRAINT fk_alm_v3_stress_asset_scenario FOREIGN KEY (stress_scenario_id) REFERENCES alm_v3_stress_scenarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
