CREATE TABLE IF NOT EXISTS s2_scr_results_real (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  captive_id INT NOT NULL,
  scenario_id INT NULL,
  reference_run_id BIGINT UNSIGNED NULL,
  snapshot_date DATE NOT NULL,
  snapshot_year_month CHAR(7) NOT NULL,
  own_funds_mode VARCHAR(16) NOT NULL DEFAULT 'auto',
  own_funds_manual_input_eur DECIMAL(18,2) NULL,
  own_funds_source_used VARCHAR(16) NOT NULL DEFAULT 'proxy',
  own_funds_eligible DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_non_life DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_counterparty DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_market DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_operational DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_bscr DECIMAL(18,2) NOT NULL DEFAULT 0,
  scr_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  mcr DECIMAL(18,2) NOT NULL DEFAULT 0,
  solvency_ratio_pct DECIMAL(10,4) NULL,
  methodology_version VARCHAR(128) NULL,
  engine_config_json JSON NULL,
  calc_scope_json JSON NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'calculated',
  created_by_user_id INT NULL,
  created_by_name VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_s2_real_captive_snapshot (captive_id, snapshot_date),
  KEY idx_s2_real_year_month (captive_id, snapshot_year_month),
  KEY idx_s2_real_reference_run (reference_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS s2_scr_inputs_non_life_real (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  real_result_id BIGINT UNSIGNED NOT NULL,
  captive_id INT NOT NULL,
  snapshot_date DATE NOT NULL,
  id_branch INT NOT NULL,
  s2_code VARCHAR(8) NULL,
  branch_label VARCHAR(255) NULL,
  premium_volume DECIMAL(18,2) NOT NULL DEFAULT 0,
  reserve_volume DECIMAL(18,2) NOT NULL DEFAULT 0,
  cat_exposure DECIMAL(18,2) NOT NULL DEFAULT 0,
  counterparty_exposure DECIMAL(18,2) NOT NULL DEFAULT 0,
  sigma_premium DECIMAL(10,6) NOT NULL DEFAULT 0,
  sigma_reserve DECIMAL(10,6) NOT NULL DEFAULT 0,
  corr_group_code VARCHAR(16) NULL,
  source_breakdown_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_s2_real_input_branch (real_result_id, id_branch),
  KEY idx_s2_real_input_snapshot (captive_id, snapshot_date),
  KEY idx_s2_real_input_s2_code (s2_code),
  CONSTRAINT fk_s2_real_inputs_result
    FOREIGN KEY (real_result_id) REFERENCES s2_scr_results_real(id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
